### ISSUE TITLE
Framebuffer and window size aren't matching

### ISSUE THREAD

**Issue by bryphe** [bryphe/revery#59]
This was reported by @jordwalke - I believe it was on a Macbook Pro. On initial run of the examples, the framebuffer isn't matching the window size:

https://media.discordapp.net/attachments/452388437635366916/514025866305601537/Screen_Shot_2018-11-19_at_2.33.20_AM.png

The autocomplete should be taking up the entire space of the window (there should be no 'cornflower blue').

After resize, the rendering correctly fills the window. This suggests there is a mismatch between how we are determining the framebuffer size on initial creation and on resize.

**Comment by Cryza** [comment]
I just had a similar artifact when trying out the `Bin` example:

![image](https://user-images.githubusercontent.com/4516798/48980112-0bae5c80-f0c5-11e8-920b-cb4cb1fbf05c.png)

One thing that caught my eye is the fact that the actual content only occupies the lower left quarter of the window. To me, this looks a lot like a scaling issue where the two dimensions are off by a factor of 2 exactly. Maybe even this has something to do with layout pixels vs native pixels, i.e. what we would call `devicePixelRatio` on the web? I know for a fact that my `devicePixelRatio` is exactly 2.

**Comment by bryphe** [comment]
> To me, this looks a lot like a scaling issue where the two dimensions are off by a factor of 2 exactly. Maybe even this has something to do with layout pixels vs native pixels, i.e. what we would call devicePixelRatio on the web? I know for a fact that my devicePixelRatio is exactly 2.

Yes, I think this is actually

**Comment by Cryza** [comment]
Wow, that was quick 🐎 

I just tested on the newest master and didn't have the issue anymore:

<img width="912" alt="screenshot 2018-11-26 at 09 42 04" src="https://user-images.githubusercontent.com/4516798/49002373-b7a48600-f15f-11e8-828c-fb81d55a6817.png">

Thanks for fixing! I guess you can close the issue now ✌️

**Comment by bryphe** [comment]
Sweet, thanks for confirming the fix @Cryza ! 💯
