### ISSUE TITLE
Build fails in Windows WSL environment

### ISSUE THREAD

**Issue by kyldvs** [bryphe/revery#82]
In windows in WSL I am getting this errors after doing an `esy install` then `esy build`:

https://gist.github.com/kyldvs/d25559a3f880cd2ad474bbbf0d1d875c

**Comment by kyldvs** [comment]
It looks like this gets me past this breakage:

```
sudo apt-get install xorg-dev libglu1-mesa-dev
```

Found in: https://github.com/openMVG/openMVG/issues/85

**Comment by dineshdhotrad** [comment]
Hello,
https://youtube.com/playlist?list=PLSsp6nX9eDuUdrCPVkucRNuzmFSiIrd2V
Look through this video tutorial you might be able to figure out some outcome.
Thank You.😊
